run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gosec
    - unconvert
    - goconst
    - goimports
    - misspell
    - prealloc
    - gocritic
    - gofmt
    - revive
    - exportloopref

issues:
  exclude-use-default: false
  exclude:
    - G104 # Errors unhandled
    - G103 # Use of unsafe calls should be audited
    - G204 # Subprocess launched with variable
    - G304 # Potential file inclusion via variable
    - G306 # WriteFile permissions 0600 or less to be audited
    - G307 # Deferring unsafe method "Close" on type "*os.File" to be audited
